"""initial schema

Revision ID: f795ad534a27
Revises: 
Create Date: 2025-07-21 07:51:31.806677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f795ad534a27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'overdue'), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent'), nullable=True),
    sa.Column('ai_analyzed_priority', sa.Enum('low', 'medium', 'high', 'urgent'), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('assigned_email', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
